services:
  mongodb:
    image: mongo
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: ShouldBeStoredInSecretsManagementTool123
    ports:
      - 27019:27017
    container_name: mongodb_container
    networks:
      - app-network

  sql_server:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ShouldBeStoredInSecretsManagementTool123"
    ports:
      - "1433:1433"
    container_name: sql_server_container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
