version: '3.7'

services:
  sql_server_container:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ShouldBeStoredInSecretsManagementTool123"
    ports:
      - "1433:1433"
    container_name: sql_server_container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
